name: development
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  repo-level:
     runs-on: self-hosted
     steps: 
       - name: list the variables at repo level
         run: |
            echo  "Hello ! The Variable at repo-level is ${{ vars.DEV_ENV_VAR }}"                        

                        
